export { default as Contact } from "./Contact"
export { default as Footer } from "./Footer"
export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as Services } from "./Services"
export { default as ThreeDBackground } from "./ThreeDBackground"
export { default as Works } from "./Works"
